# Конфигурация golangci-lint для качественного анализа Go кода

run:
  # Таймаут выполнения анализа
  timeout: 5m
  
  # Какие файлы анализировать
  tests: true
  
  # Пропуск автогенерированных файлов
  skip-files:
    - "\\.pb\\.go$"
    - "\\.gen\\.go$"
  
  # Директории для анализа
  skip-dirs:
    - vendor
    - .git
    - .github

# Настройки линтеров
linters-settings:
  # Проверка цикломатической сложности
  cyclop:
    max-complexity: 15
    package-average: 10.0
    skip-tests: true

  # Проверка когнитивной сложности
  gocognit:
    min-complexity: 20

  # Проверка длины строк
  lll:
    line-length: 120
    tab-width: 4

  # Проверка именования
  revive:
    min-confidence: 0.8
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
      - name: var-declaration
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else

  # Проверка неиспользуемых переменных
  unused:
    check-exported: false

  # Проверка ошибок
  errcheck:
    check-type-assertions: true
    check-blank: false

  # Проверка форматирования
  gofumpt:
    lang-version: "1.22"
    extra-rules: true

  # Проверка безопасности
  gosec:
    excludes:
      - G204  # Subprocess launched with variable
      - G304  # File path provided as taint input
    confidence: medium
    severity: medium

# Включенные линтеры
linters:
  enable:
    - bodyclose          # Проверка закрытия HTTP response body
    - cyclop            # Цикломатическая сложность
    - dupl              # Дублирование кода
    - durationcheck     # Проверка duration в time.Sleep
    - errcheck          # Проверка обработки ошибок
    - errname           # Именование типов ошибок
    - errorlint         # Проверка error wrapping
    - exhaustive        # Проверка полноты switch statements
    - exportloopref     # Проверка экспорта переменных из циклов
    - gocognit          # Когнитивная сложность
    - goconst           # Повторяющиеся строки
    - gocritic          # Множество проверок
    - gofmt             # Форматирование кода
    - gofumpt           # Улучшенное форматирование
    - goheader          # Заголовки файлов
    - goimports         # Импорты
    - gomnd             # Магические числа
    - gosec             # Безопасность
    - gosimple          # Упрощение кода
    - govet             # go vet
    - ineffassign       # Неэффективные присваивания
    - lll               # Длина строк
    - misspell          # Опечатки в комментариях
    - nakedret          # Голые возвраты
    - nestif            # Глубина вложенности if
    - nilerr            # Возврат nil error
    - nolintlint        # Проверка //nolint директив
    - prealloc          # Предаллокация слайсов
    - predeclared       # Переопределение встроенных идентификаторов
    - revive            # Замена golint
    - staticcheck       # Статический анализ
    - typecheck         # Проверка типов
    - unconvert         # Ненужные конверсии типов
    - unparam           # Неиспользуемые параметры
    - unused            # Неиспользуемый код
    - whitespace        # Лишние пробелы

  disable:
    - deadcode          # deprecated
    - structcheck       # deprecated
    - varcheck          # deprecated
    - interfacer        # deprecated
    - maligned          # deprecated
    - scopelint         # deprecated

# Исключения
issues:
  # Исключить определенные проблемы
  exclude-rules:
    # Исключить длинные строки в тестах
    - path: _test\.go
      linters:
        - lll
        - dupl
        - gomnd
    
    # Исключить magic numbers в main.go
    - path: main\.go
      linters:
        - gomnd
    
    # Исключить некоторые проверки для простых функций
    - text: "cyclomatic complexity"
      linters:
        - gocyclo
        - cyclop
  
  # Показывать все найденные проблемы
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Не исключать новые проблемы
  new: false
  
  # Исключить определенные директории
  exclude-dirs:
    - vendor
    - .git

# Вывод результатов
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true